### ISSUE TITLE
Crash on win7 x64 from iOS5 devices

### ISSUE THREAD

**Issue by cbarbara** [fgp/AirReceiver#3]
Can't seem to get this up and running when try to connect from an iOS5 device.
The server crashes with the following stack trace:

```
java -jar AirReceiver-1.2.one-jar.jar
Nov 13, 2011 12:20:52 AM org.phlo.AirReceiver.AirReceiver main
INFO: Launched RTSP service on port 5000
Nov 13, 2011 12:21:03 AM org.phlo.AirReceiver.AirReceiver main
Nov 13, 2011 12:21:08 AM org.phlo.AirReceiver.AirTunesCrytography getCipher
INFO: Using SPI class org.bouncycastle.jce.provider.JCERSACipher$PKCS1v1_5Padding for RSA/None/PKCS1Padding
Nov 13, 2011 12:21:08 AM org.phlo.AirReceiver.AirTunesCrytography getCipher
INFO: Using SPI class org.bouncycastle.jce.provider.JCERSACipher$NoPadding for RSA/None/OAEPWithSHA1AndMGF1Padding
Nov 13, 2011 12:21:08 AM org.phlo.AirReceiver.RtspLoggingHandler channelConnected
INFO: Client /192.168.1.241:50591 connected on /192.168.1.243:5000
Nov 13, 2011 12:21:08 AM org.phlo.AirReceiver.ExceptionLoggingHandler exceptionCaught
WARNING: Handler raised exception
org.phlo.AirReceiver.ProtocolException: Cannot parse SDP a's setting min-latency:11025
        at org.phlo.AirReceiver.RaopAudioHandler.announceReceived(RaopAudioHandler.java:366)
        at org.phlo.AirReceiver.RaopAudioHandler.messageReceived(RaopAudioHandler.java:232)
        at org.phlo.AirReceiver.RaopRtspOptionsHandler.messageReceived(RaopRtspOptionsHandler.java:53)
        at org.phlo.AirReceiver.RaopRtspHeaderHandler.messageReceived(RaopRtspHeaderHandler.java:55)
        at org.phlo.AirReceiver.RaopRtspChallengeResponseHandler.messageReceived(RaopRtspChallengeResponseHandler.java:77)
        at org.phlo.AirReceiver.RtspErrorResponseHandler.messageReceived(RtspErrorResponseHandler.java:45)
        at org.phlo.AirReceiver.RtspLoggingHandler.messageReceived(RtspLoggingHandler.java:69)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:522)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:506)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:443)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:69)
        at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:316)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)
Nov 13, 2011 12:21:08 AM org.phlo.AirReceiver.RaopAudioHandler channelClosed
INFO: RTSP connection was shut down, closing RTP channels and audio output queue
```

**Comment by fgp** [comment]
Hm, seems that iOS sends additional options in it's SDP session announcement. AirReceiver probably should simply ignore those, instead of erroring out. Will fix.

**Comment by fgp** [comment]
Fixed, the problem was the hyphen in min-latency. Fix will be included in version 1.3, to be released shortly (i.e., today)

**Comment by tehceh** [comment]
Care to re-package? Or are there any instructions for how to package?

**Comment by tehceh** [comment]
So, I built it with mvn from MAIN but I'm still getting an exception over min-latency and also one regarding the client trying to use UDP. In the meantime, I've built shairport, which appears to work well.

**Comment by sirecontrol** [comment]
Any chance of 1.3 with the fix in for this? Still issues with IOS6
